export default {
    TICK: 'TICK',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    RESET: 'RESET',

    LOAD: 'LOAD',
    SET_SESSION: 'SET_SESSION',

    DEVICE_INITIALISATION_ERROR: 'DEVICE_INITIALISATION_ERROR',
    DEVICE_AUTHENTICATION_ERROR: 'DEVICE_AUTHENTICATION_ERROR',
    ACCOUNT_ERROR: 'ACCOUNT_ERROR',
    PLAYBACK_ERROR: 'PLAYBACK_ERROR',
    DEVICE_READY: 'DEVICE_READY',
    DEVICE_NOT_READY: 'DEVICE_NOT_READY',
    PLAYER_STATE_CHANGED: 'PLAYER_STATE_CHANGED',

    PLAY_TRACK: 'PLAY_TRACK',
    PLAY_TRACK_SUCCESS: 'PLAY_TRACK_SUCCESS',
    MUTE_PLAYBACK: 'MUTE_PLAYBACK',
    UNMUTE_PLAYBACK: 'UNMUTE_PLAYBACK',
    FETCH_PLAYING_CONTEXT_SUCCESS: 'FETCH_PLAYING_CONTEXT_SUCCESS'
}
