// flow-typed signature: ead93e87f0a29e9d371cd300d388dee8
// flow-typed version: <<STUB>>/@types/jest-environment-puppeteer_v2.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest-environment-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest-environment-puppeteer' {
  declare module.exports: any;
}
