// flow-typed signature: 62ad0a115f4d97fa3661268a9152cfde
// flow-typed version: <<STUB>>/@types/jest-environment-puppeteer_v2.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest-environment-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest-environment-puppeteer' {
  declare module.exports: any;
}
