// flow-typed signature: 6cc00cfe79c6cb69375e5fb51cee4585
// flow-typed version: <<STUB>>/@types/jest_v22.2.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
