// flow-typed signature: b6d66e4e36d393497984918eaff995a3
// flow-typed version: <<STUB>>/@types/puppeteer_v1.3.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/puppeteer' {
  declare module.exports: any;
}
