// flow-typed signature: 836dbde313528786b624c45f2c3ef08a
// flow-typed version: <<STUB>>/antd-scss-theme-plugin_v^1.0.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'antd-scss-theme-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'antd-scss-theme-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'antd-scss-theme-plugin/build/dist/lib/antdLessLoader' {
  declare module.exports: any;
}

declare module 'antd-scss-theme-plugin/build/dist/lib/antdSassLoader' {
  declare module.exports: any;
}

declare module 'antd-scss-theme-plugin/build/dist/lib/extractVariablesLessPlugin' {
  declare module.exports: any;
}

declare module 'antd-scss-theme-plugin/build/dist/lib/index' {
  declare module.exports: any;
}

declare module 'antd-scss-theme-plugin/build/dist/lib/loaderUtils' {
  declare module.exports: any;
}

declare module 'antd-scss-theme-plugin/build/dist/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'antd-scss-theme-plugin/build/dist/lib/antdLessLoader.js' {
  declare module.exports: $Exports<'antd-scss-theme-plugin/build/dist/lib/antdLessLoader'>;
}
declare module 'antd-scss-theme-plugin/build/dist/lib/antdSassLoader.js' {
  declare module.exports: $Exports<'antd-scss-theme-plugin/build/dist/lib/antdSassLoader'>;
}
declare module 'antd-scss-theme-plugin/build/dist/lib/extractVariablesLessPlugin.js' {
  declare module.exports: $Exports<'antd-scss-theme-plugin/build/dist/lib/extractVariablesLessPlugin'>;
}
declare module 'antd-scss-theme-plugin/build/dist/lib/index.js' {
  declare module.exports: $Exports<'antd-scss-theme-plugin/build/dist/lib/index'>;
}
declare module 'antd-scss-theme-plugin/build/dist/lib/loaderUtils.js' {
  declare module.exports: $Exports<'antd-scss-theme-plugin/build/dist/lib/loaderUtils'>;
}
declare module 'antd-scss-theme-plugin/build/dist/lib/utils.js' {
  declare module.exports: $Exports<'antd-scss-theme-plugin/build/dist/lib/utils'>;
}
