// flow-typed signature: e6d372303fc55f781664ad828096eddf
// flow-typed version: <<STUB>>/jest-puppeteer_v2.4.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
