// flow-typed signature: df8c9fb355dc4e4052e7c77c30b383a7
// flow-typed version: <<STUB>>/next-progressbar_v^1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-progressbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-progressbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-progressbar/index' {
  declare module.exports: $Exports<'next-progressbar'>;
}
declare module 'next-progressbar/index.js' {
  declare module.exports: $Exports<'next-progressbar'>;
}
