// flow-typed signature: e09823fd5e78134f0640bd63bbf099f5
// flow-typed version: <<STUB>>/postcss-functions_v^3.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-functions/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-functions/dist/lib/helpers' {
  declare module.exports: any;
}

declare module 'postcss-functions/dist/lib/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-functions/dist/index.js' {
  declare module.exports: $Exports<'postcss-functions/dist/index'>;
}
declare module 'postcss-functions/dist/lib/helpers.js' {
  declare module.exports: $Exports<'postcss-functions/dist/lib/helpers'>;
}
declare module 'postcss-functions/dist/lib/transformer.js' {
  declare module.exports: $Exports<'postcss-functions/dist/lib/transformer'>;
}
