// flow-typed signature: bdd47868ca5e2d7b00a90d37b7722134
// flow-typed version: <<STUB>>/sails_v^1.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sails'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sails' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sails/accessible/generate' {
  declare module.exports: any;
}

declare module 'sails/accessible/rc' {
  declare module.exports: any;
}

declare module 'sails/bin/private/patched-commander' {
  declare module.exports: any;
}

declare module 'sails/bin/private/read-repl-history-and-start-transcribing' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-console' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-debug-console' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-debug' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-deploy' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-generate' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-inspect' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-lift' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-new' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-run' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-upgrade' {
  declare module.exports: any;
}

declare module 'sails/bin/sails-www' {
  declare module.exports: any;
}

declare module 'sails/bin/sails' {
  declare module.exports: any;
}

declare module 'sails/errors/fatal' {
  declare module.exports: any;
}

declare module 'sails/errors/index' {
  declare module.exports: any;
}

declare module 'sails/errors/warn' {
  declare module.exports: any;
}

declare module 'sails/lib/app/configuration/default-hooks' {
  declare module.exports: any;
}

declare module 'sails/lib/app/configuration/index' {
  declare module.exports: any;
}

declare module 'sails/lib/app/configuration/load' {
  declare module.exports: any;
}

declare module 'sails/lib/app/configuration/rc' {
  declare module.exports: any;
}

declare module 'sails/lib/app/get-actions' {
  declare module.exports: any;
}

declare module 'sails/lib/app/get-route-for' {
  declare module.exports: any;
}

declare module 'sails/lib/app/get-url-for' {
  declare module.exports: any;
}

declare module 'sails/lib/app/index' {
  declare module.exports: any;
}

declare module 'sails/lib/app/lift' {
  declare module.exports: any;
}

declare module 'sails/lib/app/load' {
  declare module.exports: any;
}

declare module 'sails/lib/app/lower' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/after' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/bootstrap' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/checkGruntConfig' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/controller/help-register-action' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/controller/load-action-modules' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/exposeGlobals' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/initialize' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/inspect' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/isLocalSailsValid' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/isSailsAppSync' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/loadHooks' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/toJSON' {
  declare module.exports: any;
}

declare module 'sails/lib/app/private/toString' {
  declare module.exports: any;
}

declare module 'sails/lib/app/register-action-middleware' {
  declare module.exports: any;
}

declare module 'sails/lib/app/register-action' {
  declare module.exports: any;
}

declare module 'sails/lib/app/reload-actions' {
  declare module.exports: any;
}

declare module 'sails/lib/app/request' {
  declare module.exports: any;
}

declare module 'sails/lib/app/Sails' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/add' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/create' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/destroy' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/find' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/findOne' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/populate' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/remove' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/replace' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actions/update' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/actionUtil' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/formatUsageError' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/onRoute' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/blueprints/parse-blueprint-options' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/helpers/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/helpers/private/iterate-helpers' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/helpers/private/load-helpers' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/http/get-configured-http-middleware-fns' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/http/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/http/initialize' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/http/start' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/http/view' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/i18n/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/logger/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/logger/ship' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/moduleloader/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/policies/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/pubsub/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/request/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/request/locals' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/request/metadata' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/request/param' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/request/params.all' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/request/qualifiers' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/request/validate' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/defaults/badRequest' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/defaults/forbidden' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/defaults/negotiate' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/defaults/notFound' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/defaults/ok' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/defaults/serverError' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/responses/onRoute' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/security/cors/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/security/cors/set-headers' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/security/cors/set-preflight-config' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/security/csrf/grant-csrf-token' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/security/csrf/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/security/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/services/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/session/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/userconfig/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/userhooks/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/configure' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/default-view-rendering-fn' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/escape-html-entities-deep' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/get-implicit-defaults' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/html-scriptify' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/index' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/onRoute' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/render' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/res.view' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/stat-views' {
  declare module.exports: any;
}

declare module 'sails/lib/hooks/views/unescape-html-entities-deep-lite.min.string' {
  declare module.exports: any;
}

declare module 'sails/lib/index' {
  declare module.exports: any;
}

declare module 'sails/lib/router/bind' {
  declare module.exports: any;
}

declare module 'sails/lib/router/bindDefaultHandlers' {
  declare module.exports: any;
}

declare module 'sails/lib/router/index' {
  declare module.exports: any;
}

declare module 'sails/lib/router/mock-req' {
  declare module.exports: any;
}

declare module 'sails/lib/router/mock-res' {
  declare module.exports: any;
}

declare module 'sails/lib/router/req' {
  declare module.exports: any;
}

declare module 'sails/lib/router/res' {
  declare module.exports: any;
}

declare module 'sails/lib/util/check-origin-url' {
  declare module.exports: any;
}

declare module 'sails/lib/util/detect-verb' {
  declare module.exports: any;
}

declare module 'sails/test/benchmarks/helpers/benchmarx' {
  declare module.exports: any;
}

declare module 'sails/test/benchmarks/sails.load.test' {
  declare module.exports: any;
}

declare module 'sails/test/benchmarks/sails.request.generic.test' {
  declare module.exports: any;
}

declare module 'sails/test/fixtures/constants' {
  declare module.exports: any;
}

declare module 'sails/test/fixtures/customHooks' {
  declare module.exports: any;
}

declare module 'sails/test/fixtures/middleware' {
  declare module.exports: any;
}

declare module 'sails/test/helpers/RouteFactory.helper' {
  declare module.exports: any;
}

declare module 'sails/test/helpers/router' {
  declare module.exports: any;
}

declare module 'sails/test/helpers/sails' {
  declare module.exports: any;
}

declare module 'sails/test/helpers/test-spawning-sails-child-process-in-cwd' {
  declare module.exports: any;
}

declare module 'sails/test/helpers/test-spawning-sails-lift-child-process-in-cwd' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/blueprints/initialize.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/http/initialize.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/pubsub/initialize.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/request/initialize.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/request/req.metadata.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/request/req.options.sticky.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/views/intialize.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/views/res.render.i18n' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/views/res.view.test' {
  declare module.exports: any;
}

declare module 'sails/test/hooks/views/skipAssets.test' {
  declare module.exports: any;
}

declare module 'sails/test/init' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/hooks/installable/add-policy/index' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/hooks/installable/shout/index' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/EmptyController' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/PetController' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/QuizController' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/TestController' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/UserController' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/UserProfileController' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/ViewTestController' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/models/Empty' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/models/Pet' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/models/Quiz' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/models/Test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/models/User' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/models/UserProfile' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/policies/error_policy' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/policies/fake_auth' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/api/services/TestService' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/sampleapp/config/local' {
  declare module.exports: any;
}

declare module 'sails/test/integration/fixtures/users' {
  declare module.exports: any;
}

declare module 'sails/test/integration/generate.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/globals.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/helpers/appHelper' {
  declare module.exports: any;
}

declare module 'sails/test/integration/helpers/httpHelper' {
  declare module.exports: any;
}

declare module 'sails/test/integration/helpers/socketHelper' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.3rdparty.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.blueprints.action.routes.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.blueprints.blacklist.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.blueprints.index.routes.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.blueprints.restful.routes.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.blueprints.shortcut.routes.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.cors.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.csrf.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.helpers.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.i18n.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.policies.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.pubsub.modelEvents.noSubscribers.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.pubsub.modelEvents.subscribers.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.sockets.interpreter.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.userconfig.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hook.views.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/hooks.user.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/lift.https.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/lift.lower.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/lift.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.404.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.500.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.compression.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.cookieParser.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.favicon.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.handleBodyParserError.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.sails.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.session.redis.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.session.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.startRequestTimer.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/middleware.static.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/new.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/router.params.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/router.specifiedRoutes.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/router.viewRendering.test' {
  declare module.exports: any;
}

declare module 'sails/test/integration/www.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/app.getRouteFor.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/app.getUrlFor.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/app.initializeHooks.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/app.lower.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/App.prototype.load.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/app.registerAction.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/app.reloadActions.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/bootstrap.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/controller.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/req.errors.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/req.session.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/req.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/router.bind.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/router.ordering.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/router.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/router.unbind.test' {
  declare module.exports: any;
}

declare module 'sails/test/unit/virtual-request-interpreter.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sails/accessible/generate.js' {
  declare module.exports: $Exports<'sails/accessible/generate'>;
}
declare module 'sails/accessible/rc.js' {
  declare module.exports: $Exports<'sails/accessible/rc'>;
}
declare module 'sails/bin/private/patched-commander.js' {
  declare module.exports: $Exports<'sails/bin/private/patched-commander'>;
}
declare module 'sails/bin/private/read-repl-history-and-start-transcribing.js' {
  declare module.exports: $Exports<'sails/bin/private/read-repl-history-and-start-transcribing'>;
}
declare module 'sails/bin/sails-console.js' {
  declare module.exports: $Exports<'sails/bin/sails-console'>;
}
declare module 'sails/bin/sails-debug-console.js' {
  declare module.exports: $Exports<'sails/bin/sails-debug-console'>;
}
declare module 'sails/bin/sails-debug.js' {
  declare module.exports: $Exports<'sails/bin/sails-debug'>;
}
declare module 'sails/bin/sails-deploy.js' {
  declare module.exports: $Exports<'sails/bin/sails-deploy'>;
}
declare module 'sails/bin/sails-generate.js' {
  declare module.exports: $Exports<'sails/bin/sails-generate'>;
}
declare module 'sails/bin/sails-inspect.js' {
  declare module.exports: $Exports<'sails/bin/sails-inspect'>;
}
declare module 'sails/bin/sails-lift.js' {
  declare module.exports: $Exports<'sails/bin/sails-lift'>;
}
declare module 'sails/bin/sails-new.js' {
  declare module.exports: $Exports<'sails/bin/sails-new'>;
}
declare module 'sails/bin/sails-run.js' {
  declare module.exports: $Exports<'sails/bin/sails-run'>;
}
declare module 'sails/bin/sails-upgrade.js' {
  declare module.exports: $Exports<'sails/bin/sails-upgrade'>;
}
declare module 'sails/bin/sails-www.js' {
  declare module.exports: $Exports<'sails/bin/sails-www'>;
}
declare module 'sails/bin/sails.js' {
  declare module.exports: $Exports<'sails/bin/sails'>;
}
declare module 'sails/errors/fatal.js' {
  declare module.exports: $Exports<'sails/errors/fatal'>;
}
declare module 'sails/errors/index.js' {
  declare module.exports: $Exports<'sails/errors/index'>;
}
declare module 'sails/errors/warn.js' {
  declare module.exports: $Exports<'sails/errors/warn'>;
}
declare module 'sails/lib/app/configuration/default-hooks.js' {
  declare module.exports: $Exports<'sails/lib/app/configuration/default-hooks'>;
}
declare module 'sails/lib/app/configuration/index.js' {
  declare module.exports: $Exports<'sails/lib/app/configuration/index'>;
}
declare module 'sails/lib/app/configuration/load.js' {
  declare module.exports: $Exports<'sails/lib/app/configuration/load'>;
}
declare module 'sails/lib/app/configuration/rc.js' {
  declare module.exports: $Exports<'sails/lib/app/configuration/rc'>;
}
declare module 'sails/lib/app/get-actions.js' {
  declare module.exports: $Exports<'sails/lib/app/get-actions'>;
}
declare module 'sails/lib/app/get-route-for.js' {
  declare module.exports: $Exports<'sails/lib/app/get-route-for'>;
}
declare module 'sails/lib/app/get-url-for.js' {
  declare module.exports: $Exports<'sails/lib/app/get-url-for'>;
}
declare module 'sails/lib/app/index.js' {
  declare module.exports: $Exports<'sails/lib/app/index'>;
}
declare module 'sails/lib/app/lift.js' {
  declare module.exports: $Exports<'sails/lib/app/lift'>;
}
declare module 'sails/lib/app/load.js' {
  declare module.exports: $Exports<'sails/lib/app/load'>;
}
declare module 'sails/lib/app/lower.js' {
  declare module.exports: $Exports<'sails/lib/app/lower'>;
}
declare module 'sails/lib/app/private/after.js' {
  declare module.exports: $Exports<'sails/lib/app/private/after'>;
}
declare module 'sails/lib/app/private/bootstrap.js' {
  declare module.exports: $Exports<'sails/lib/app/private/bootstrap'>;
}
declare module 'sails/lib/app/private/checkGruntConfig.js' {
  declare module.exports: $Exports<'sails/lib/app/private/checkGruntConfig'>;
}
declare module 'sails/lib/app/private/controller/help-register-action.js' {
  declare module.exports: $Exports<'sails/lib/app/private/controller/help-register-action'>;
}
declare module 'sails/lib/app/private/controller/load-action-modules.js' {
  declare module.exports: $Exports<'sails/lib/app/private/controller/load-action-modules'>;
}
declare module 'sails/lib/app/private/exposeGlobals.js' {
  declare module.exports: $Exports<'sails/lib/app/private/exposeGlobals'>;
}
declare module 'sails/lib/app/private/initialize.js' {
  declare module.exports: $Exports<'sails/lib/app/private/initialize'>;
}
declare module 'sails/lib/app/private/inspect.js' {
  declare module.exports: $Exports<'sails/lib/app/private/inspect'>;
}
declare module 'sails/lib/app/private/isLocalSailsValid.js' {
  declare module.exports: $Exports<'sails/lib/app/private/isLocalSailsValid'>;
}
declare module 'sails/lib/app/private/isSailsAppSync.js' {
  declare module.exports: $Exports<'sails/lib/app/private/isSailsAppSync'>;
}
declare module 'sails/lib/app/private/loadHooks.js' {
  declare module.exports: $Exports<'sails/lib/app/private/loadHooks'>;
}
declare module 'sails/lib/app/private/toJSON.js' {
  declare module.exports: $Exports<'sails/lib/app/private/toJSON'>;
}
declare module 'sails/lib/app/private/toString.js' {
  declare module.exports: $Exports<'sails/lib/app/private/toString'>;
}
declare module 'sails/lib/app/register-action-middleware.js' {
  declare module.exports: $Exports<'sails/lib/app/register-action-middleware'>;
}
declare module 'sails/lib/app/register-action.js' {
  declare module.exports: $Exports<'sails/lib/app/register-action'>;
}
declare module 'sails/lib/app/reload-actions.js' {
  declare module.exports: $Exports<'sails/lib/app/reload-actions'>;
}
declare module 'sails/lib/app/request.js' {
  declare module.exports: $Exports<'sails/lib/app/request'>;
}
declare module 'sails/lib/app/Sails.js' {
  declare module.exports: $Exports<'sails/lib/app/Sails'>;
}
declare module 'sails/lib/hooks/blueprints/actions/add.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/add'>;
}
declare module 'sails/lib/hooks/blueprints/actions/create.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/create'>;
}
declare module 'sails/lib/hooks/blueprints/actions/destroy.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/destroy'>;
}
declare module 'sails/lib/hooks/blueprints/actions/find.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/find'>;
}
declare module 'sails/lib/hooks/blueprints/actions/findOne.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/findOne'>;
}
declare module 'sails/lib/hooks/blueprints/actions/populate.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/populate'>;
}
declare module 'sails/lib/hooks/blueprints/actions/remove.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/remove'>;
}
declare module 'sails/lib/hooks/blueprints/actions/replace.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/replace'>;
}
declare module 'sails/lib/hooks/blueprints/actions/update.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actions/update'>;
}
declare module 'sails/lib/hooks/blueprints/actionUtil.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/actionUtil'>;
}
declare module 'sails/lib/hooks/blueprints/formatUsageError.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/formatUsageError'>;
}
declare module 'sails/lib/hooks/blueprints/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/index'>;
}
declare module 'sails/lib/hooks/blueprints/onRoute.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/onRoute'>;
}
declare module 'sails/lib/hooks/blueprints/parse-blueprint-options.js' {
  declare module.exports: $Exports<'sails/lib/hooks/blueprints/parse-blueprint-options'>;
}
declare module 'sails/lib/hooks/helpers/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/helpers/index'>;
}
declare module 'sails/lib/hooks/helpers/private/iterate-helpers.js' {
  declare module.exports: $Exports<'sails/lib/hooks/helpers/private/iterate-helpers'>;
}
declare module 'sails/lib/hooks/helpers/private/load-helpers.js' {
  declare module.exports: $Exports<'sails/lib/hooks/helpers/private/load-helpers'>;
}
declare module 'sails/lib/hooks/http/get-configured-http-middleware-fns.js' {
  declare module.exports: $Exports<'sails/lib/hooks/http/get-configured-http-middleware-fns'>;
}
declare module 'sails/lib/hooks/http/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/http/index'>;
}
declare module 'sails/lib/hooks/http/initialize.js' {
  declare module.exports: $Exports<'sails/lib/hooks/http/initialize'>;
}
declare module 'sails/lib/hooks/http/start.js' {
  declare module.exports: $Exports<'sails/lib/hooks/http/start'>;
}
declare module 'sails/lib/hooks/http/view.js' {
  declare module.exports: $Exports<'sails/lib/hooks/http/view'>;
}
declare module 'sails/lib/hooks/i18n/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/i18n/index'>;
}
declare module 'sails/lib/hooks/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/index'>;
}
declare module 'sails/lib/hooks/logger/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/logger/index'>;
}
declare module 'sails/lib/hooks/logger/ship.js' {
  declare module.exports: $Exports<'sails/lib/hooks/logger/ship'>;
}
declare module 'sails/lib/hooks/moduleloader/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/moduleloader/index'>;
}
declare module 'sails/lib/hooks/policies/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/policies/index'>;
}
declare module 'sails/lib/hooks/pubsub/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/pubsub/index'>;
}
declare module 'sails/lib/hooks/request/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/request/index'>;
}
declare module 'sails/lib/hooks/request/locals.js' {
  declare module.exports: $Exports<'sails/lib/hooks/request/locals'>;
}
declare module 'sails/lib/hooks/request/metadata.js' {
  declare module.exports: $Exports<'sails/lib/hooks/request/metadata'>;
}
declare module 'sails/lib/hooks/request/param.js' {
  declare module.exports: $Exports<'sails/lib/hooks/request/param'>;
}
declare module 'sails/lib/hooks/request/params.all.js' {
  declare module.exports: $Exports<'sails/lib/hooks/request/params.all'>;
}
declare module 'sails/lib/hooks/request/qualifiers.js' {
  declare module.exports: $Exports<'sails/lib/hooks/request/qualifiers'>;
}
declare module 'sails/lib/hooks/request/validate.js' {
  declare module.exports: $Exports<'sails/lib/hooks/request/validate'>;
}
declare module 'sails/lib/hooks/responses/defaults/badRequest.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/defaults/badRequest'>;
}
declare module 'sails/lib/hooks/responses/defaults/forbidden.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/defaults/forbidden'>;
}
declare module 'sails/lib/hooks/responses/defaults/negotiate.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/defaults/negotiate'>;
}
declare module 'sails/lib/hooks/responses/defaults/notFound.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/defaults/notFound'>;
}
declare module 'sails/lib/hooks/responses/defaults/ok.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/defaults/ok'>;
}
declare module 'sails/lib/hooks/responses/defaults/serverError.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/defaults/serverError'>;
}
declare module 'sails/lib/hooks/responses/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/index'>;
}
declare module 'sails/lib/hooks/responses/onRoute.js' {
  declare module.exports: $Exports<'sails/lib/hooks/responses/onRoute'>;
}
declare module 'sails/lib/hooks/security/cors/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/security/cors/index'>;
}
declare module 'sails/lib/hooks/security/cors/set-headers.js' {
  declare module.exports: $Exports<'sails/lib/hooks/security/cors/set-headers'>;
}
declare module 'sails/lib/hooks/security/cors/set-preflight-config.js' {
  declare module.exports: $Exports<'sails/lib/hooks/security/cors/set-preflight-config'>;
}
declare module 'sails/lib/hooks/security/csrf/grant-csrf-token.js' {
  declare module.exports: $Exports<'sails/lib/hooks/security/csrf/grant-csrf-token'>;
}
declare module 'sails/lib/hooks/security/csrf/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/security/csrf/index'>;
}
declare module 'sails/lib/hooks/security/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/security/index'>;
}
declare module 'sails/lib/hooks/services/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/services/index'>;
}
declare module 'sails/lib/hooks/session/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/session/index'>;
}
declare module 'sails/lib/hooks/userconfig/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/userconfig/index'>;
}
declare module 'sails/lib/hooks/userhooks/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/userhooks/index'>;
}
declare module 'sails/lib/hooks/views/configure.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/configure'>;
}
declare module 'sails/lib/hooks/views/default-view-rendering-fn.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/default-view-rendering-fn'>;
}
declare module 'sails/lib/hooks/views/escape-html-entities-deep.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/escape-html-entities-deep'>;
}
declare module 'sails/lib/hooks/views/get-implicit-defaults.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/get-implicit-defaults'>;
}
declare module 'sails/lib/hooks/views/html-scriptify.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/html-scriptify'>;
}
declare module 'sails/lib/hooks/views/index.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/index'>;
}
declare module 'sails/lib/hooks/views/onRoute.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/onRoute'>;
}
declare module 'sails/lib/hooks/views/render.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/render'>;
}
declare module 'sails/lib/hooks/views/res.view.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/res.view'>;
}
declare module 'sails/lib/hooks/views/stat-views.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/stat-views'>;
}
declare module 'sails/lib/hooks/views/unescape-html-entities-deep-lite.min.string.js' {
  declare module.exports: $Exports<'sails/lib/hooks/views/unescape-html-entities-deep-lite.min.string'>;
}
declare module 'sails/lib/index.js' {
  declare module.exports: $Exports<'sails/lib/index'>;
}
declare module 'sails/lib/router/bind.js' {
  declare module.exports: $Exports<'sails/lib/router/bind'>;
}
declare module 'sails/lib/router/bindDefaultHandlers.js' {
  declare module.exports: $Exports<'sails/lib/router/bindDefaultHandlers'>;
}
declare module 'sails/lib/router/index.js' {
  declare module.exports: $Exports<'sails/lib/router/index'>;
}
declare module 'sails/lib/router/mock-req.js' {
  declare module.exports: $Exports<'sails/lib/router/mock-req'>;
}
declare module 'sails/lib/router/mock-res.js' {
  declare module.exports: $Exports<'sails/lib/router/mock-res'>;
}
declare module 'sails/lib/router/req.js' {
  declare module.exports: $Exports<'sails/lib/router/req'>;
}
declare module 'sails/lib/router/res.js' {
  declare module.exports: $Exports<'sails/lib/router/res'>;
}
declare module 'sails/lib/util/check-origin-url.js' {
  declare module.exports: $Exports<'sails/lib/util/check-origin-url'>;
}
declare module 'sails/lib/util/detect-verb.js' {
  declare module.exports: $Exports<'sails/lib/util/detect-verb'>;
}
declare module 'sails/test/benchmarks/helpers/benchmarx.js' {
  declare module.exports: $Exports<'sails/test/benchmarks/helpers/benchmarx'>;
}
declare module 'sails/test/benchmarks/sails.load.test.js' {
  declare module.exports: $Exports<'sails/test/benchmarks/sails.load.test'>;
}
declare module 'sails/test/benchmarks/sails.request.generic.test.js' {
  declare module.exports: $Exports<'sails/test/benchmarks/sails.request.generic.test'>;
}
declare module 'sails/test/fixtures/constants.js' {
  declare module.exports: $Exports<'sails/test/fixtures/constants'>;
}
declare module 'sails/test/fixtures/customHooks.js' {
  declare module.exports: $Exports<'sails/test/fixtures/customHooks'>;
}
declare module 'sails/test/fixtures/middleware.js' {
  declare module.exports: $Exports<'sails/test/fixtures/middleware'>;
}
declare module 'sails/test/helpers/RouteFactory.helper.js' {
  declare module.exports: $Exports<'sails/test/helpers/RouteFactory.helper'>;
}
declare module 'sails/test/helpers/router.js' {
  declare module.exports: $Exports<'sails/test/helpers/router'>;
}
declare module 'sails/test/helpers/sails.js' {
  declare module.exports: $Exports<'sails/test/helpers/sails'>;
}
declare module 'sails/test/helpers/test-spawning-sails-child-process-in-cwd.js' {
  declare module.exports: $Exports<'sails/test/helpers/test-spawning-sails-child-process-in-cwd'>;
}
declare module 'sails/test/helpers/test-spawning-sails-lift-child-process-in-cwd.js' {
  declare module.exports: $Exports<'sails/test/helpers/test-spawning-sails-lift-child-process-in-cwd'>;
}
declare module 'sails/test/hooks/blueprints/initialize.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/blueprints/initialize.test'>;
}
declare module 'sails/test/hooks/http/initialize.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/http/initialize.test'>;
}
declare module 'sails/test/hooks/pubsub/initialize.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/pubsub/initialize.test'>;
}
declare module 'sails/test/hooks/request/initialize.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/request/initialize.test'>;
}
declare module 'sails/test/hooks/request/req.metadata.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/request/req.metadata.test'>;
}
declare module 'sails/test/hooks/request/req.options.sticky.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/request/req.options.sticky.test'>;
}
declare module 'sails/test/hooks/views/intialize.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/views/intialize.test'>;
}
declare module 'sails/test/hooks/views/res.render.i18n.js' {
  declare module.exports: $Exports<'sails/test/hooks/views/res.render.i18n'>;
}
declare module 'sails/test/hooks/views/res.view.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/views/res.view.test'>;
}
declare module 'sails/test/hooks/views/skipAssets.test.js' {
  declare module.exports: $Exports<'sails/test/hooks/views/skipAssets.test'>;
}
declare module 'sails/test/init.js' {
  declare module.exports: $Exports<'sails/test/init'>;
}
declare module 'sails/test/integration/fixtures/hooks/installable/add-policy/index.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/hooks/installable/add-policy/index'>;
}
declare module 'sails/test/integration/fixtures/hooks/installable/shout/index.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/hooks/installable/shout/index'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/EmptyController.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/controllers/EmptyController'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/PetController.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/controllers/PetController'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/QuizController.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/controllers/QuizController'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/TestController.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/controllers/TestController'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/UserController.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/controllers/UserController'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/UserProfileController.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/controllers/UserProfileController'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/controllers/ViewTestController.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/controllers/ViewTestController'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/models/Empty.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/models/Empty'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/models/Pet.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/models/Pet'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/models/Quiz.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/models/Quiz'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/models/Test.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/models/Test'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/models/User.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/models/User'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/models/UserProfile.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/models/UserProfile'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/policies/error_policy.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/policies/error_policy'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/policies/fake_auth.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/policies/fake_auth'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/api/services/TestService.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/api/services/TestService'>;
}
declare module 'sails/test/integration/fixtures/sampleapp/config/local.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/sampleapp/config/local'>;
}
declare module 'sails/test/integration/fixtures/users.js' {
  declare module.exports: $Exports<'sails/test/integration/fixtures/users'>;
}
declare module 'sails/test/integration/generate.test.js' {
  declare module.exports: $Exports<'sails/test/integration/generate.test'>;
}
declare module 'sails/test/integration/globals.test.js' {
  declare module.exports: $Exports<'sails/test/integration/globals.test'>;
}
declare module 'sails/test/integration/helpers/appHelper.js' {
  declare module.exports: $Exports<'sails/test/integration/helpers/appHelper'>;
}
declare module 'sails/test/integration/helpers/httpHelper.js' {
  declare module.exports: $Exports<'sails/test/integration/helpers/httpHelper'>;
}
declare module 'sails/test/integration/helpers/socketHelper.js' {
  declare module.exports: $Exports<'sails/test/integration/helpers/socketHelper'>;
}
declare module 'sails/test/integration/hook.3rdparty.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.3rdparty.test'>;
}
declare module 'sails/test/integration/hook.blueprints.action.routes.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.blueprints.action.routes.test'>;
}
declare module 'sails/test/integration/hook.blueprints.blacklist.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.blueprints.blacklist.test'>;
}
declare module 'sails/test/integration/hook.blueprints.index.routes.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.blueprints.index.routes.test'>;
}
declare module 'sails/test/integration/hook.blueprints.restful.routes.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.blueprints.restful.routes.test'>;
}
declare module 'sails/test/integration/hook.blueprints.shortcut.routes.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.blueprints.shortcut.routes.test'>;
}
declare module 'sails/test/integration/hook.cors.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.cors.test'>;
}
declare module 'sails/test/integration/hook.csrf.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.csrf.test'>;
}
declare module 'sails/test/integration/hook.helpers.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.helpers.test'>;
}
declare module 'sails/test/integration/hook.i18n.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.i18n.test'>;
}
declare module 'sails/test/integration/hook.policies.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.policies.test'>;
}
declare module 'sails/test/integration/hook.pubsub.modelEvents.noSubscribers.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.pubsub.modelEvents.noSubscribers.test'>;
}
declare module 'sails/test/integration/hook.pubsub.modelEvents.subscribers.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.pubsub.modelEvents.subscribers.test'>;
}
declare module 'sails/test/integration/hook.sockets.interpreter.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.sockets.interpreter.test'>;
}
declare module 'sails/test/integration/hook.userconfig.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.userconfig.test'>;
}
declare module 'sails/test/integration/hook.views.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hook.views.test'>;
}
declare module 'sails/test/integration/hooks.user.test.js' {
  declare module.exports: $Exports<'sails/test/integration/hooks.user.test'>;
}
declare module 'sails/test/integration/lift.https.test.js' {
  declare module.exports: $Exports<'sails/test/integration/lift.https.test'>;
}
declare module 'sails/test/integration/lift.lower.test.js' {
  declare module.exports: $Exports<'sails/test/integration/lift.lower.test'>;
}
declare module 'sails/test/integration/lift.test.js' {
  declare module.exports: $Exports<'sails/test/integration/lift.test'>;
}
declare module 'sails/test/integration/middleware.404.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.404.test'>;
}
declare module 'sails/test/integration/middleware.500.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.500.test'>;
}
declare module 'sails/test/integration/middleware.compression.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.compression.test'>;
}
declare module 'sails/test/integration/middleware.cookieParser.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.cookieParser.test'>;
}
declare module 'sails/test/integration/middleware.favicon.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.favicon.test'>;
}
declare module 'sails/test/integration/middleware.handleBodyParserError.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.handleBodyParserError.test'>;
}
declare module 'sails/test/integration/middleware.sails.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.sails.test'>;
}
declare module 'sails/test/integration/middleware.session.redis.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.session.redis.test'>;
}
declare module 'sails/test/integration/middleware.session.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.session.test'>;
}
declare module 'sails/test/integration/middleware.startRequestTimer.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.startRequestTimer.test'>;
}
declare module 'sails/test/integration/middleware.static.test.js' {
  declare module.exports: $Exports<'sails/test/integration/middleware.static.test'>;
}
declare module 'sails/test/integration/new.test.js' {
  declare module.exports: $Exports<'sails/test/integration/new.test'>;
}
declare module 'sails/test/integration/router.params.test.js' {
  declare module.exports: $Exports<'sails/test/integration/router.params.test'>;
}
declare module 'sails/test/integration/router.specifiedRoutes.test.js' {
  declare module.exports: $Exports<'sails/test/integration/router.specifiedRoutes.test'>;
}
declare module 'sails/test/integration/router.viewRendering.test.js' {
  declare module.exports: $Exports<'sails/test/integration/router.viewRendering.test'>;
}
declare module 'sails/test/integration/www.test.js' {
  declare module.exports: $Exports<'sails/test/integration/www.test'>;
}
declare module 'sails/test/unit/app.getRouteFor.test.js' {
  declare module.exports: $Exports<'sails/test/unit/app.getRouteFor.test'>;
}
declare module 'sails/test/unit/app.getUrlFor.test.js' {
  declare module.exports: $Exports<'sails/test/unit/app.getUrlFor.test'>;
}
declare module 'sails/test/unit/app.initializeHooks.test.js' {
  declare module.exports: $Exports<'sails/test/unit/app.initializeHooks.test'>;
}
declare module 'sails/test/unit/app.lower.test.js' {
  declare module.exports: $Exports<'sails/test/unit/app.lower.test'>;
}
declare module 'sails/test/unit/App.prototype.load.test.js' {
  declare module.exports: $Exports<'sails/test/unit/App.prototype.load.test'>;
}
declare module 'sails/test/unit/app.registerAction.test.js' {
  declare module.exports: $Exports<'sails/test/unit/app.registerAction.test'>;
}
declare module 'sails/test/unit/app.reloadActions.test.js' {
  declare module.exports: $Exports<'sails/test/unit/app.reloadActions.test'>;
}
declare module 'sails/test/unit/bootstrap.test.js' {
  declare module.exports: $Exports<'sails/test/unit/bootstrap.test'>;
}
declare module 'sails/test/unit/controller.test.js' {
  declare module.exports: $Exports<'sails/test/unit/controller.test'>;
}
declare module 'sails/test/unit/req.errors.test.js' {
  declare module.exports: $Exports<'sails/test/unit/req.errors.test'>;
}
declare module 'sails/test/unit/req.session.test.js' {
  declare module.exports: $Exports<'sails/test/unit/req.session.test'>;
}
declare module 'sails/test/unit/req.test.js' {
  declare module.exports: $Exports<'sails/test/unit/req.test'>;
}
declare module 'sails/test/unit/router.bind.test.js' {
  declare module.exports: $Exports<'sails/test/unit/router.bind.test'>;
}
declare module 'sails/test/unit/router.ordering.test.js' {
  declare module.exports: $Exports<'sails/test/unit/router.ordering.test'>;
}
declare module 'sails/test/unit/router.test.js' {
  declare module.exports: $Exports<'sails/test/unit/router.test'>;
}
declare module 'sails/test/unit/router.unbind.test.js' {
  declare module.exports: $Exports<'sails/test/unit/router.unbind.test'>;
}
declare module 'sails/test/unit/virtual-request-interpreter.test.js' {
  declare module.exports: $Exports<'sails/test/unit/virtual-request-interpreter.test'>;
}
